<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BPOAmericas.TestDeveloper.API\BPOAmericas.TestDeveloper.API.csproj" />
    <ProjectReference Include="..\BPOAmericas.TestDeveloper.Common\BPOAmericas.TestDeveloper.Common.csproj" />
  </ItemGroup>

</Project>
